### ISSUE TITLE
Unable to print std::string when printing multiple variables.

### ISSUE THREAD

**Issue by shi-yan** [sharkdp/dbg-macro#58] opened 2019-09-21 20:13 UTC
The following fails to print the content of t->message

```c++
  struct Test{
    std::string message;
  };

  std::shared_ptr<Test> t(new Test);
  t->message = "hello";
  dbg("Request from", t->message, 23);
```

expected output:

`[..xxx.cpp:24 (helloWorld)] "Request from", t->message = "hello" (std::string), 23 = 23 (int)`

actual output:

`[..xxx.cpp:24 (helloWorld)] "Request from", t->message, 23 = 23 (int)`

**Comment by sharkdp** [comment] 2019-09-21 20:29
Thank you for your report.

This is basically a duplicate of #2 because `dbg(…)` doesn't currently support multiple arguments. What happens is that
```c++
"Request from", t->message, 2
```
is treated as a comma-operator expression which evaluates to `2`. This is why this line (confusingly) prints `"Request from", t->message, 23 = 23`.

**Closed** 2019-09-23 17:51 UTC
